---
name: PHPUnit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  PHPUnit:
    uses: discoverygarden/phpunit-action/.github/workflows/phpunit.yml@test_reusable
    secrets: inherit
